@set allusersprofile=c:\programdata
@set appdata=c:\users\hakob\appdata\roaming
@set asl.log=destination=file
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=lenovo-y40
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio 10.0\common7\ide\
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework35version=v3.5
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\hakob
@set include=c:\program files (x86)\microsoft visual studio 10.0\vc\include;c:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include;c:\program files (x86)\microsoft sdks\windows\v7.0a\include
@set lib=c:\program files (x86)\microsoft visual studio 10.0\vc\lib;c:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\lib;c:\program files (x86)\microsoft sdks\windows\v7.0a\lib
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;c:\windows\microsoft.net\framework\v3.5;c:\program files (x86)\microsoft visual studio 10.0\vc\lib;c:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\lib
@set localappdata=c:\users\hakob\appdata\local
@set logonserver=\\lenovo-y40
@set msbuildsdkspath=c:\windows\microsoft.net\framework64\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set msmpi_bin=c:\program files\microsoft mpi\bin\
@set number_of_processors=4
@set onedrive=c:\users\hakob\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio 10.0\vstsdb\deploy;c:\program files (x86)\microsoft visual studio 10.0\common7\ide\;c:\program files (x86)\microsoft visual studio 10.0\vc\bin;c:\program files (x86)\microsoft visual studio 10.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;c:\windows\microsoft.net\framework\v3.5;c:\program files (x86)\microsoft visual studio 10.0\vc\vcpackages;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 10.0\team tools\performance tools;c:\program files (x86)\microsoft sdks\windows\v7.0a\bin\netfx 4.0 tools;c:\program files (x86)\microsoft sdks\windows\v7.0a\bin;c:\program files\microsoft mpi\bin\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\skype\phone\;c:\program files\dotnet\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\openvpn\bin;c:\program files (x86)\microsoft sql server\100\tools\binn\;c:\program files\microsoft sql server\100\tools\binn\;c:\program files\microsoft sql server\100\dts\binn\;d:\git\cmd;c:\program files\mysql\mysql utilities 1.6\;c:\users\hakob\appdata\local\microsoft\windowsapps;c:\program files\microsoft vs code\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 61 stepping 4, genuineintel
@set processor_level=6
@set processor_revision=3d04
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\windows\microsoft.net\framework64\
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\hakob\appdata\local\temp
@set tmp=c:\users\hakob\appdata\local\temp
@set userdomain=lenovo-y40
@set userdomain_roamingprofile=lenovo-y40
@set username=hakob
@set userprofile=c:\users\hakob
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 10.0\vc\
@set visualstudiodir=c:\users\hakob\documents\visual studio 2010
@set vs100comntools=c:\program files (x86)\microsoft visual studio 10.0\common7\tools\
@set vs150entcomntools=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 10.0\
@set windir=c:\windows
@set windowssdkdir=c:\program files (x86)\microsoft sdks\windows\v7.0a\
@set fsharpinstalldir=C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\

@call "cl.exe" @"C:\Users\hakob\Desktop\calculator 02.03.18\calc_Expression\calc_ExpressionDlg.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1